#!/bin/bash
# NEWS ANALYZER - QUICK REFERENCE CHEATSHEET

echo "=========================================="
echo "📊 NEWS ANALYZER COMMANDS"
echo "=========================================="
echo ""

echo "🚀 START/STOP/RESTART:"
echo "  pm2 start ecosystem.config.js --only sankeo-analyzer"
echo "  pm2 stop sankeo-analyzer"
echo "  pm2 restart sankeo-analyzer"
echo "  pm2 delete sankeo-analyzer"
echo ""

echo "📋 MONITORING:"
echo "  pm2 status                        # Check all services"
echo "  pm2 logs sankeo-analyzer          # Live logs (Ctrl+C to exit)"
echo "  pm2 logs sankeo-analyzer -n 100   # Last 100 lines"
echo "  pm2 monit                         # Interactive monitor"
echo ""

echo "🏥 HEALTH CHECK:"
echo "  python -m src.worker.analyzer_health"
echo "  bash scripts/monitor_analyzer.sh"
echo ""

echo "🗄️ DATABASE QUERIES:"
echo ""
echo "  # Count messages processed"
echo "  SELECT COUNT(*) FROM crypto_news;"
echo ""
echo "  # Top sources by message count"
echo "  SELECT source_name, COUNT(*) as count"
echo "  FROM crypto_news GROUP BY source_name ORDER BY count DESC;"
echo ""
echo "  # High weight messages (>70)"
echo "  SELECT id, source_name, final_weight FROM crypto_news"
echo "  WHERE final_weight >= 70 ORDER BY final_weight DESC;"
echo ""
echo "  # Messages by sentiment"
echo "  SELECT layer2_sentiment, COUNT(*) FROM crypto_news"
echo "  GROUP BY layer2_sentiment;"
echo ""
echo "  # Duplicate analysis"
echo "  SELECT content_hash, COUNT(*) as occurrences FROM news_duplicates"
echo "  GROUP BY content_hash ORDER BY occurrences DESC;"
echo ""

echo "⚙️ DEPLOYMENT:"
echo "  bash scripts/deploy_analyzer.sh   # Full deployment with migration"
echo "  python -m alembic upgrade head    # Apply migrations only"
echo ""

echo "🧪 LOCAL TESTING:"
echo "  python scripts/test_filter.py     # Test with sample messages"
echo ""

echo "📊 QUEUE STATS:"
echo "  redis-cli LLEN queue:raw_messages       # Messages pending"
echo "  redis-cli LRANGE queue:raw_messages 0 -1 | head  # View first messages"
echo ""

echo "🔍 DEBUGGING:"
echo "  pm2 describe sankeo-analyzer           # Process details"
echo "  pm2 env sankeo-analyzer                # Environment variables"
echo "  pm2 save                               # Save PM2 config"
echo "  pm2 startup                            # Auto-start on reboot"
echo ""

echo "=========================================="
echo "📖 For full documentation: cat ANALYZER.md"
echo "=========================================="
